### ISSUE TITLE
streaming bulk helper does not catch client.bulk exceptions

### ISSUE THREAD

**Issue by pmajmudar** [elasticsearch/elasticsearch-py#166]
Hi,

I am using the streaming_bulk helper (with raise_on_error set to False).

However occasionally I get an unhandled exception in the code, coming from the 
client.bulk call in the helper function (e.g. an Elasticsearch MemoryError or timeout error). In this case the streaming_bulk method does not catch this exception and so my code exits.

My code is basically:

```python
results_gen = streaming_bulk(es, doc_iter, chunk_size=100)
for success, result in result_gen:
   print success, result
```
```doc_iter``` is a generator that I pass in - Ideally I would like it to just continue iterating through my iterable. It also means I can't catch this exception myself at a higher level.

Ideally I'd like a try, except block around the ```client.bulk``` call in the streaming_bulk method. Any exceptions could then be returned by the yield statement in streaming_bulk.

Any thoughts?

**Comment by HonzaKral** [comment]
I think I have implemented it in the bulk_exception branch. I "think" so because there are no tests yet, but if you could have a look I'd be glad. Thanks!

**Comment by pmajmudar** [comment]
Brilliant, thanks! I'll take a look

**Comment by pmajmudar** [comment]
Hi,

Thanks for implementing the changes. I've had a look at the code and tested the branch with my code.

I'd quite like to be able to catch additional exceptions other than a TransportError (e.g. ConnectionError etc.). In addition I occasionally get a Python MemoryError exception that is propagated (clearly this is a bit more fatal and possibly not recoverable) - but in some cases its recoverable.

Would you like me to submit a pull request (on your branch?) with my minor changes to handle these cases?

**Comment by HonzaKral** [comment]
We cannot catch all exceptions in this manner, especially not `MemoryError` etc. The only one where it would make some sense is `ConnectionError`, but only there it's limited - the only way a connection error would be raised is if the client has already retried and still got the error. That means that the next request will also most likely fail so essentially we will just start throwing away data very quickly. This is something I'd consider non-recoverable and therefore didn't try to catch it. What do you think?

**Comment by pmajmudar** [comment]
OK that's probably fair. The transport exception you catch is good for me.

I've run a test with your changes and it seemed to work - the generator no longer quits, but simply yields the errors for failed documents and carries on (which is great!)

I still need to work out which documents failed for logging purposes - as the result is yielded with no information about the chunk / doc that was attempted - its hard for me to understand from my logs what data actually caused the fail. 

Can you also yield the doc itself for each failed action? Or have the option to do so?

**Comment by HonzaKral** [comment]
I am yielding a very similar structure to what a failed operation would result in, including all the metadata (index, type, id, ...) specified. I guess I could also attach the data somehow, but not sure if I should.
