### ISSUE TITLE
Elasticsearch Dictionary with elasticsearch-py

### ISSUE THREAD

**Issue by abhillman** [elasticsearch/elasticsearch-py#172]
Supposing I have a query such as the following:

```
es.search(index='movies', doc_type='movie', q='genre: drama')
```

Is there a way to emit the JSON that is sent to the elasticsearch instance? Thanks!

**Comment by HonzaKral** [comment]
The client doesn't create any json or anything, it just sends everything you give it. In this case it makes a request equivalent to:

    curl "localhost:9200/movies/movie/_search?q=genre: drama"

You can configure the logging to show you exactly what's being sent (0). Note that you might want to look into Elasticsearch DSL (1) for a tool that will help you create the queries.

0 - http://elasticsearch-py.readthedocs.org/en/master/#logging
1 - https://github.com/elasticsearch/elasticsearch-dsl-py

**Comment by abhillman** [comment]
This is great. Thanks, Honza.
