### ISSUE TITLE
Specify a query to reindex only the documents that belong satisfy a query, in reindex helper function.

### ISSUE THREAD

**Issue by syllogismos** [elasticsearch/elasticsearch-py#174]
It would be great if I were to be able to specify a query when reindexing, so that I can control what documents go into a new index. Instead of just all the documents.

If you don't specify the query it will just reindex all the documents.

**Comment by syllogismos** [comment]
Here is the pull request https://github.com/elasticsearch/elasticsearch-py/pull/173

**Comment by HonzaKral** [comment]
this has been fixed by 87bba04
