### ISSUE TITLE
Getting "unable to sniff hosts" Transport Exception randomly when trying to index new data into my cluster..

### ISSUE THREAD

**Issue by syllogismos** [elasticsearch/elasticsearch-py#175]
Earlier we used to get 

```
'ConnectionError(\'N/A\', "(<urllib3.connection.HTTPConnection object at 0x7faea2f68950>,
 \'Connection to ***.**.**.*** timed out. (connect timeout=10)\')", ConnectTimeoutError(<urllib3.connection.HTTPConnection 
object at 0x7faea03cdb90>, \'Connection to ***.**.**.*** timed out. (connect timeout=10)\'))
```

We increased the timeout from the default 10 to 600 in our index function.

```
es.index(index = indexName, doc_type = typeName, body = body, timeout = 600)
```

And now we are getting the new Transport Exception saying `unable to sniff hosts`. And it seems to be random. How do we fix it. How can it be unreliable like this. Are we doing any thing wrong?

Is it compulsory to give ips of all nodes in my cluster to initialize ES in using elasticsearch-py?

**Comment by HonzaKral** [comment]
The `index` parameter is elasticsearch's internal timeout that has no bearing on the request itself, for it use `request_timeout`. Example can be found at http://elasticsearch-py.readthedocs.org/en/master/api.html#timeout

The unable to sniff hosts exception occurs when we are instructed to sniff hosts and the sniffing process fails. It should not be random, but depends on your settings. If you have a less-reliable network, try raising the `sniff_timeout` parameter of `Elasticsearch()`. Raising it to 10 should be more than sufficient.

Hope this helps

**Comment by syllogismos** [comment]
Random in the sense, I have no idea how to reproduce those exceptions. But on production I'm getting those errors briefly from time to time.. like 3-4 index requests fail at a time at least 3 times a day


so what you recommend is 

from http://elasticsearch-py.readthedocs.org/en/master/api.html#elasticsearch 
`es = Elasticsearch(['node1, node2], sniffer_timeout=10)`

and 

from http://elasticsearch-py.readthedocs.org/en/master/api.html#elasticsearch.Elasticsearch.index
`response = es.index(index = indexName, doc_type = typeName, body = data, request_timeout = 600)`

Thanks.

**Comment by HonzaKral** [comment]
No, `sniff_timeout` instead of `sniffer_timeout`. One controls the timeout of the sniff requests, other controls the period between the sniff requests.

**Comment by syllogismos** [comment]
It's not in the documentation.. Sorry I thought yours was a typo.. Will fix it..

**Comment by HonzaKral** [comment]
Closing this since there is a workaround.

**Comment by lcwy220** [comment]
Excuse me, I also happened to meet this problem, so I want to ask you how to solve this problem?

Thank you.

**Comment by HonzaKral** [comment]
The solution is to make the `sniff_timeout` higher - passing in a number in seconds. `10` should be a very safe value

**Comment by smetj** [comment]
@HonzaKral In my case I'm using Elasticsearch-2.4.4 and the python elasticsearch==2.4.1 library.
I cannot connect to my cluster using sniffing. Setting the suggested `sniff_timeout` does not help.

Instead it seems that (at least on centos7, python2.7.5) urllib3 found in site-packages is used instead of the embedded urllib3 library?

Currently `python-urllib3-1.10.2-2.el7_1` is installed I have to upgrade to python-urllib3-1.22 in order to fix the problem.

**Comment by wx-txc** [comment]
very good!
