### ISSUE TITLE
Add support for passing custom auth objects to RequestsHttpConnection

### ISSUE THREAD

**Issue by jonahbull** [elasticsearch/elasticsearch-py#178]
Our internal authentication mechanisms require us to make use of requests' [custom authentication objects](http://docs.python-requests.org/en/latest/user/advanced/#custom-authentication). It'd be great if we could add support for this to the [RequestsHttpConnection](https://github.com/elasticsearch/elasticsearch-py/blob/master/elasticsearch/connection/http_requests.py#L12) class.

Ideally it would work much as the existing support for http_auth does. That is, add another kwarg for the custom authentication to `__init__` and set `self.session.auth` to the custom auth object. I'd be happy to put together a PR if my suggestion sounds worthwhile.

**Comment by HonzaKral** [comment]
This seems like a fairly fringe use case and can be implemented very well outside of `elasticsearch-py` - just subclass `RequestHttpConnection`, add the relevant code to `__init__` after calling `super().__init__` and then pass the class to `Elasticsearch` as `connection_class`. Would that be ok for you?

**Comment by jonahbull** [comment]
I'd already gone the subclassing route but was curious about how fringe the use case was. Now I know :) I'll just keep using the subclass. Thanks for the quick response @HonzaKral .

**Comment by HonzaKral** [comment]
Let's see if anyone else comments with the use case, it's not a big change but I would like to avoid adding additional kwargs as much as possible.
