### ISSUE TITLE
delete_by_query for entire doc_type throws ValidationError

### ISSUE THREAD

**Issue by phill-tornroth** [elasticsearch/elasticsearch-py#179]
When I run `es_conn.delete_by_query(my_index_name, doc_type=my_doc_type)`, ES is throwing me
 `TransportError(400, u'ActionRequestValidationException[Validation Failed: 1: source is missing;]')`

Is this intentional? ES 1.40, elasticsearch-py 1.1.1

**Comment by phill-tornroth** [comment]
Aaaaand, nevermind. I see that adding the argument `body={'query':{'match_all': {}}}` sorts us out. Apologies.

**Comment by HonzaKral** [comment]
There is also a dedicated API for deleting an entire doc_type (including the mapping) in case that is what you were after - http://elasticsearch-py.readthedocs.org/en/master/api.html#elasticsearch.client.IndicesClient.delete_mapping

**Comment by phill-tornroth** [comment]
Oh thanks! In this case I was actually specifically looking to delete records but preserve mapping. FWIW this is in my personal elasticsearch backend for haystack, which I know you've done plenty of work on. I settled on clear() doing a delete_by_query instead of deleting the mapping because some really nasty race conditions can happen otherwise where records for that doctype might be inserted between clearing and re-adding the mapping, causing mapping conflicts and huge explosions :)

If there happens to be (now or in the future) a way to wipe out a doctype and replace it's mapping in a serialized fashion, that'd be handy for achieving the original intent.

**Comment by HonzaKral** [comment]
Have you looked at `elasticsearch-dsl` (0)? It provides an easier integration with elasticsearch without the limitations of haystack. It doesn't have Django integration (yet), but it could help.

Unfortunately Elasticsearch doesn't have much support for transactional behavior. what I would suggest there is use individual indices and use aliases to switch them around. Also deleting an entire index is a very lightweight operation compared to `delete_by_query`.

0 - https://github.com/elasticsearch/elasticsearch-dsl-py

**Comment by phill-tornroth** [comment]
Oh wow, I hadn't seen this. It looks really awesome! If by django integration you mean view/form/template stuff, I've never used that side of haystack anyways. As for hooking up modification signals and updating the backend, I've always had to roll my own versions of those things anyways.

I have seen mention of the alias-swapping strategy now that you mention it. It seemed a little overwhelming to implement behind haystack, if I understood it correctly. It'd be really neat if elasticsearch-dsl could help manage aliased 'versions' of the index behind the scenes, seems like the sort of pattern that a library could help spare some pain and stumbling on.

Thanks much!
