### ISSUE TITLE
doc: function arguments sequence swapped for indecies.put_alias method

### ISSUE THREAD

**Issue by houqp** [elasticsearch/elasticsearch-py#183]
In the doc string, index was listed as the first argument, while in the source code, it's the second one.

**Comment by HonzaKral** [comment]
Yes, this is one of the many reasons we highly recommend people to use keyword arguments when working with `elasticsearch-py` - order of arguments may change at any release since we use positional or keyword arguments to determine required/optional status of any given parameter.
