### ISSUE TITLE
Add indices param to helper.scan function

### ISSUE THREAD

**Issue by jpshelley** [elasticsearch/elasticsearch-py#186]
The helper.scan function that sits on top of the scroll function, doesn't allow for an index. So by default I'm assuming it searched for _all. 

Does it make sense to allow a parameter for this?

**Comment by HonzaKral** [comment]
All keyword argument that you pass into the `scan` function will be passed through to the `search` method so you can easily specify: `scan(es, index=['index_one', 'index_two'])`

So no need to add the parameter, but maybe some documentation and more examples of use might be helpful, I will look into it.

**Comment by jpshelley** [comment]
@HonzaKral Thanks for the quick reply! Appreciate it!
