### ISSUE TITLE
batch processing support

### ISSUE THREAD

**Issue by avelino** [elasticsearch/elasticsearch-py#188]
Today the drive not the batch support?

http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/_batch_processing.html#_batch_processing

**Comment by HonzaKral** [comment]
It does as the `bulk` api is fully supported and there is also a helper (1) to make it easier, as mentioned in the docs (2).

1 - http://elasticsearch-py.readthedocs.org/en/master/helpers.html#elasticsearch.helpers.streaming_bulk
2 - http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-bulk.html
