### ISSUE TITLE
No module named helpers

### ISSUE THREAD

**Issue by rajeshyogeshwar** [elasticsearch/elasticsearch-py#193]
I have latest version of elasticsearch python client, but still I get an error saying no module named helpers found. Is there something else that needs to be installed?
I just do following steps
import elasticsearch
elasticsearch.helpers.bulk('with all necessary params')

**Comment by HonzaKral** [comment]
You need to import the helpers module first, either by calling `import elasticsearch.helpers` and the using as you described, or `from elasticsearch import helpers` and then using `helpers.bulk`.

I usually just import the stuff I want to use:

    from elasticsearch import Elasticsearch
    from elasticsearch.helpers import bulk

    es = Elasticsearch()
    bulk(es, ...)
