### ISSUE TITLE
Order preserving scrolling and sorting

### ISSUE THREAD

**Issue by drorata** [elasticsearch/elasticsearch-py#197]
In [scan](http://elasticsearch-py.readthedocs.org/en/latest/helpers.html#elasticsearch.helpers.scan) helper, it is not clear what is the "preserved order" that is maintained if `preserve_order` is set to `True`. Can you elaborate on the matter? Is it equivalent to run a scrolling without set the the type to `scan`? 

Furthermore, for the `sort` parameter of [scroll](http://elasticsearch-py.readthedocs.org/en/latest/api.html#elasticsearch.Elasticsearch.search) to have an effect I guess the `preserve_order` must be set to `True`. Is it correct?

**Comment by HonzaKral** [comment]
Both your assumptions are correct. If you can think of how to make the documentation clearer I would be happy to hear it. Thanks!

**Comment by drorata** [comment]
Maybe something along these lines maybe?

> *Remark on order:* Note that by default `scan` does not return results in any pre-determined order. In order to have an order in the returned documents, when scrolling, the `scan` type has to be disabled; to that end use `preserve_order=True` and pass a value to the `sort` parameter.

**Comment by HonzaKral** [comment]
I will add it there, with the appropriate warning - it can really eat a lot of resources if you decide to do this. Which is exactly counter to the spirit of scan.

Thanks for the question and the suggestion!

**Comment by HonzaKral** [comment]
Added in 756298a36021ef24529115f01df6e8a4bce1567a
